version: '3.8'

services:
  starknet-kms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for development (excluding node_modules)
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./biome.json:/app/biome.json
      # Preserve the offline cache and node_modules
      - offline-cache:/app/offline-cache
    environment:
      - NODE_ENV=development
    command: dev # Default command to run

  # For running tests in isolation
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for development (excluding node_modules)
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./biome.json:/app/biome.json
      # Preserve the offline cache and node_modules
      - offline-cache:/app/offline-cache
    environment:
      - NODE_ENV=test
    command: test:unit

volumes:
  offline-cache:
    # Persist the offline cache between container runs 